### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by kartikeyahl** [I-aashishM/Optical-Character-Recogniser#4]
the link you provided for the dataset is unavailable/not opening.

**Comment by I-aashishM** [comment]
You can download the dataset from https://academictorrents.com/details/8ed33d02d6b36c389dd077ea2478cc83ad117ef3

This will be torrent file.

**Comment by kartikeyahl** [comment]
Please can you add the .csv file that you used in training the model on github

**Comment by I-aashishM** [comment]
Its uploaded in Data folder.

you can close the issue, if your issue resolved.

**Comment by kartikeyahl** [comment]
please look at what I am doing wrong, you can edit it [https://colab.research.google.com/drive/1vPQ4Er1-a24QF4E2SmMzZTChBZmv5MNQ?usp=sharing](url)

**Comment by I-aashishM** [comment]
This happens because image does not load properly. Check if the images exist in the path you give.
